config/routes.rb
Rails.application.routes.draw do
  resources :corrections
  resources :matches
  resources :leagues
  get '/leagues/:id/add/:team_id' => 'leagues#addteam'
  resources :teams

  get '/tabelle' => 'pages#tabelle'
  get '/week/:league_id/:week_id' => 'pages#week'

end

app/models/league.rb
class League < ActiveRecord::Base
	has_many :ligassos
	has_many :teams, :through => :ligassos
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy, :addteam]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show

    @teams = @league.teams

    #table0

    @tabelle0 = []
    @teams.each do |team|
      @points = 0
      @goalsScored = 0
      @goalsConceded = 0
      team.matches.each do |m|

        m.corrections.each do |c|
          if c.typeOfCorrection == 0
            if m.mirror == false
              m.real_result += c.change
            else
              m.real_result += c.mirrorchange
            end
          end
        end

        # points
        if m.team1goals > m.team2goals
          @points += 3
        elsif m.team1goals == m.team2goals
          @points += 1
        end

        # goals
        @goalsScored += m.team1goals
        @goalsConceded += m.team2goals
      end
      @goalDifference = @goalsScored - @goalsConceded
      @tabelle0.push([team.name, @points, @goalDifference, @goalsScored, @goalsConceded, team.id])
    end

    @tabelle0.sort!  { |a,b| [ b[1], b[2] ] <=> [ a[1], a[2] ] }




    #table1

    @tabelle1 = []
    @teams.each do |team|
      @points = 0
      @goalsScored = 0
      @goalsConceded = 0
      team.matches.each do |m|

        m.real_result = 0
        m.corrections.each do |c|
          if c.typeOfCorrection == 0 || c.typeOfCorrection == 1
            if m.mirror == false
              m.real_result += c.change
            else
              m.real_result += c.mirrorchange
            end
          end
        end

        # points
        if m.team1goals > m.team2goals
          @points += 3
        elsif m.team1goals == m.team2goals
          @points += 1
        end

        # goals
        @goalsScored += m.team1goals
        @goalsConceded += m.team2goals
      end
      @goalDifference = @goalsScored - @goalsConceded
      @tabelle1.push([team.name, @points, @goalDifference, @goalsScored, @goalsConceded, team.id])
    end

    @tabelle1.sort!  { |a,b| [ b[1], b[2] ] <=> [ a[1], a[2] ] }




    #table2

    @tabelle2 = []
    @teams.each do |team|
      @points = 0
      @goalsScored = 0
      @goalsConceded = 0
      team.matches.each do |m|

        m.real_result = 0
        m.corrections.each do |c|
          if c.typeOfCorrection == 0 || c.typeOfCorrection == 2
            if m.mirror == false
              m.real_result += c.change
            else
              m.real_result += c.mirrorchange
            end
          end
        end

        # points
        if m.team1goals > m.team2goals
          @points += 3
        elsif m.team1goals == m.team2goals
          @points += 1
        end

        # goals
        @goalsScored += m.team1goals
        @goalsConceded += m.team2goals
      end
      @goalDifference = @goalsScored - @goalsConceded
      @tabelle2.push([team.name, @points, @goalDifference, @goalsScored, @goalsConceded, team.id])
    end

    @tabelle2.sort!  { |a,b| [ b[1], b[2] ] <=> [ a[1], a[2] ] }




    #table3

    @tabelle3 = []
    @teams.each do |team|
      @points = 0
      @goalsScored = 0
      @goalsConceded = 0
      team.matches.each do |m|

        m.real_result = 0
        m.corrections.each do |c|
          if c.typeOfCorrection == 0 || c.typeOfCorrection == 3
            if m.mirror == false
              m.real_result += c.change
            else
              m.real_result += c.mirrorchange
            end
          end
        end

        # points
        if m.team1goals > m.team2goals
          @points += 3
        elsif m.team1goals == m.team2goals
          @points += 1
        end

        # goals
        @goalsScored += m.team1goals
        @goalsConceded += m.team2goals
      end
      @goalDifference = @goalsScored - @goalsConceded
      @tabelle3.push([team.name, @points, @goalDifference, @goalsScored, @goalsConceded, team.id])
    end

    @tabelle3.sort!  { |a,b| [ b[1], b[2] ] <=> [ a[1], a[2] ] }




    @mastertabelle = []
    @tabelle0.count.times do |x|
      @mastertabelle.push([@tabelle0[x], @tabelle1[x], @tabelle2[x], @tabelle3[x]])
    end

  end

  def addteam
    @team = Team.find(params[:team_id])
    @league.teams.push(@team)
    redirect_to @league
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:name, :endyear)
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :endyear %><br>
    <%= f.number_field :endyear %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/crazytable.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @league.name %> <%= @league.endyear-1 %>/<%= @league.endyear %></h1>


<table class="table">
  	<thead>
  		<tr>
  			<th colspan=4>
  				Real Tabelle
  			</th>
  			<th colspan=4>
  				Referee
  			</th>
  			<th colspan=4>
  				Hundred
  			</th>
  			<th colspan=4>
  				No Luck
  			</th>
  		<tr>
  			<th>Team</th>
  			<th>Points</th>
  			<th>Difference</th>
  			<th>Scored:Conceded</th>
  			<th>Team</th>
  			<th>Points</th>
  			<th>Difference</th>
  			<th>Scored:Conceded</th>
   			<th>Team</th>
  			<th>Points</th>
  			<th>Difference</th>
  			<th>Scored:Conceded</th>
    		<th>Team</th>
  			<th>Points</th>
  			<th>Difference</th>
  			<th>Scored:Conceded</th>
  		</tr>
  	</thead>
  	<tbody>
  	<% @mastertabelle.each do |place| %>
	  	<tr>
	  		<% x = 0 %>
	  		<td><%= link_to place[x][0], "/teams/#{place[x][5]}" %></td>
	  		<td><%= place[x][1] %></td>
	  		<td><%= place[x][2] %></th>
 	  		<td><%= place[x][3] %> : <%= place[x][4] %></td>

	  		<% x = 1 %>
	  		<td><%= link_to place[x][0], "/teams/#{place[x][5]}" %></td>
	  		<td><%= place[x][1] %></td>
	  		<td><%= place[x][2] %></th>
 	  		<td><%= place[x][3] %> : <%= place[x][4] %></td>

	  		<% x = 2 %>
	  		<td><%= link_to place[x][0], "/teams/#{place[x][5]}" %></td>
	  		<td><%= place[x][1] %></td>
	  		<td><%= place[x][2] %></th>
 	  		<td><%= place[x][3] %> : <%= place[x][4] %></td>

	  		<% x = 3 %>
	  		<td><%= link_to place[x][0], "/teams/#{place[x][5]}" %></td>
	  		<td><%= place[x][1] %></td>
	  		<td><%= place[x][2] %></th>
 	  		<td><%= place[x][3] %> : <%= place[x][4] %></td>
	  	</tr>
  	<% end %>
  	</tbody>
</table>

app/views/leagues/edit.html.erb
<h1>Editing League</h1>

<%= render 'form' %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leagues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Endyear</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= league.name %></td>
        <td><%= league.endyear %></td>
        <td><%= link_to 'Show', league %></td>
        <td><%= link_to 'Edit', edit_league_path(league) %></td>
        <td><%= link_to 'Destroy', league, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New League', new_league_path %>

app/views/leagues/new.html.erb
<h1>New League</h1>

<%= render 'form' %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @league.name %> <%= @league.endyear-1 %>/<%= @league.endyear %></h1>


<table class="table">
  	<thead>
  		<tr>
  			<th>
  				Real Tabelle
  			</th>
  			<th>
  				Referee
  			</th>
  			<th>
  				Hundred
  			</th>
  			<th>
  				No Luck
  			</th>

  	</thead>
  	<tbody>
  	<% @position = 1 %>
  	<% @width = 50 %>
  	<% @mastertabelle.each do |place| %>
	  	<tr>
	  		<% x = 0 %>
	  		<td>
	  			<%= @position%>. <img alt="Icon" src="/assets/<%=place[x][5]%>.png" width="<%=@width%>" />
	  		</td>

	  		<% x = 1 %>
	  		<td>
	  			<%= @position%>. <img alt="Icon" src="/assets/<%=place[x][5]%>.png" width="<%=@width%>" />
	  		</td>

	  		<% x = 2 %>
	  		<td>
	  			<%= @position%>. <img alt="Icon" src="/assets/<%=place[x][5]%>.png" width="<%=@width%>" />
	  		</td>

	  		<% x = 3 %>
	  		<td>
	  			<%= @position%>. <img alt="Icon" src="/assets/<%=place[x][5]%>.png" width="<%=@width%>" />
	  		</td>

	  		<% @position += 1%>
	  	</tr>
  	<% end %>
  	</tbody>
</table>






<% if @league.teams.count <18 %>
	<strong>This league is not complete yet. Please add teams</strong>
	<ul>
		<% Team.all.each do |team| %>
			<% unless @league.teams.include?(team) %>
				<li><%= link_to team.name, "/leagues/1/add/#{team.id}" %></li>
			<% end %>
		<% end %>
	</ul>
	<br>
<% end %>
<%= link_to 'Edit', edit_league_path(@league) %> |
<%= link_to 'Back', leagues_path %>