config/routes.rb
Rails.application.routes.draw do
  resources :corrections
  resources :matches
  resources :leagues
  get '/leagues/:id/add/:team_id' => 'leagues#addteam'
  resources :teams

  get '/tabelle' => 'pages#tabelle'
  get '/week/:league_id/:week_id' => 'pages#week'

end

app/models/match.rb
class Match < ActiveRecord::Base
	belongs_to :team
	belongs_to :league

	has_many :correctassos
	has_many :corrections, :through => :correctassos

	def team1goals
		(self.real_result - self.real_result % 10)/10
	end

	def team2goals
		self.real_result % 10
	end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
    @weeks = []
    @matches.each do |match|
      unless @weeks.include?(match.week)
        @weeks.push(match.week)
      end
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
    @matches = Match.all
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)
    @match.mirror = false
    @resulttwist = 0
    @resulttwist += ((@match.real_result % 10)*10)
    @resulttwist += ((@match.real_result - (@match.real_result % 10))/10)
    @match2 = Match.new(
      :league_id => @match.league_id,
      :week => @match.week,
      :real_result => @resulttwist,
      :team_id => @match.otherteam_id, 
      :otherteam_id => @match.team_id, 
      :mirror => true
      )

    respond_to do |format|
      if @match.save
        @match2.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    if @match.mirror == false
      @match2 = Match.find((params[:id].to_i+1).to_s)
      @match2.destroy
    else
      @match2 = Match.find((params[:id].to_i-1).to_s)
      @match2.destroy
    end
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:week, :real_result, :league_id, :team_id, :otherteam_id, :mirror)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :league_id %><br>
    <%= f.select :league_id, League.all.map{|l| [l.name, l.id]} %>
  </div>

  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week, :min => 1 %>
  </div>

  <div class="field">
    <%= f.label :team_id, "Heimteam" %></br>
    <%= f.select :team_id, Team.all.map{|t| [t.name, t.id]} %>
  </div>

  <div class="field">
    <%= f.label :otherteam_id, "Auswärtsteam" %></br>
    <%= f.select :otherteam_id, Team.all.map{|t| [t.name, t.id]} %>
  </div>


  <div class="field">
    <%= f.label :real_result %></br>
    <%= f.number_field :real_result %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Matches</h1>
<button><%= link_to 'New Match', new_match_path %></button>


<% @weeks.each do |week| %>

<h2><%= week %>. Spieltag</h2>

<table class="table">
  <thead>
    <tr>
      <th>Teams</th>
      <th>Real result</th>
      <th>Referee Corrections</th>
      <th>One Hundred</th>
      <th>No Luck</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <% if match.mirror == false && match.week == week %>
        <tr>
          <td><%= match.team.name %> vs. <%= Team.find(match.otherteam_id).name %></td>
          <td>
            <% match.corrections.each do |c| %>
              <% if c.typeOfCorrection == 0 %>
                <% match.real_result += c.change %>
              <% end %>
            <% end %>
            <%= match.team1goals %> : <%= match.team2goals %>
          </td>


          <td>
            <% @originalscore = match.real_result %>
            
            <% match.corrections.each do |c| %>
              <% if c.typeOfCorrection == 1 %>
                <% match.real_result += c.change %>
              <% end %>
            <% end %>
            
            <%= match.team1goals %> : <%= match.team2goals %><br>

            <% match.real_result = @originalscore %>
          </td>


          <td>
            <% @originalscore = match.real_result %>
            
            <% match.corrections.each do |c| %>
              <% if c.typeOfCorrection == 2 %>
                <% match.real_result += c.change %>
              <% end %>
            <% end %>
            
            <%= match.team1goals %> : <%= match.team2goals %><br>

            <% match.real_result = @originalscore %>
          </td>


          <td>
            <% @originalscore = match.real_result %>
            
            <% match.corrections.each do |c| %>
              <% if c.typeOfCorrection == 3 %>
                <% match.real_result += c.change %>
              <% end %>
            <% end %>
            
            <%= match.team1goals %> : <%= match.team2goals %><br>

            <% match.real_result = @originalscore %>
          </td>

          <td><button><%= link_to "New Correction", new_correction_path(:match_id=>match.id) %></button></td>
          <td><button><%= link_to 'Show Match Info', match %></button></td>
<!--           <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 -->        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<% end %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% unless @matches.count == 0 %>
    <div class="field">
      <%= f.label :league_id %><br>
      <%= f.select :league_id, League.all.map{|l| [l.name, l.id]}, :value => @matches.last.league_id %>
    </div>
    <div class="field">
      <%= f.label :week %><br>
      <%= f.number_field :week, :value => @matches.last.week, :min => 1 %>
      (Last entry was <%= @matches.last.week %>)
    </div>

  <% else %>
    <div class="field">
      <%= f.label :league_id %><br>
      <%= f.select :league_id, League.all.map{|l| [l.name, l.id]} %>
    </div>
    <div class="field">
      <%= f.label :week %><br>
      <%= f.number_field :week, :min => 1 %>
    </div>
  <%end %>



  <div class="field">
    <%= f.label :team_id, "Heimteam" %></br>
    <%= f.select :team_id, Team.all.map{|t| [t.name, t.id]} %>
  </div>

  <div class="field">
    <%= f.label :otherteam_id, "Auswärtsteam" %></br>
    <%= f.select :otherteam_id, Team.all.map{|t| [t.name, t.id]} %>
  </div>


  <div class="field" style='display:none'>
    <%= f.label :real_result %></br>
    <%= f.number_field :real_result, :value => 0 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>


<h1><%= @match.team.name %> vs. <%= Team.find(@match.otherteam_id).name %></h1>

<br><br>

<table class="table">
	<tr>
	  	<th>League:</th>
	  	<td><%= @match.league.name %> <%= @match.league.endyear-1 %>/<%= @match.league.endyear %></td>
	</tr>

	<tr>
	  	<th>Week:</th>
	  	<td><%= @match.week %>. Spieltag</td>
  	</tr>

</table>


<h2>Ninety Minutes and then three</h2>
<table class="table">
	<thead>
		<tr>
			<th></th>
			<th>Real Score</th>
			<th>Referee Mistakes</th>
			<th>One Hundred</th>
			<th>No Luck</th>
		</tr>
	</thead>

	<% @minutes = [] %>
	<% @match.corrections.each do |c| %>
		<% unless @minutes.include?(c.minute) %>
			<% @minutes.push(c.minute) %>
		<% end %>
	<% end %>
	<% @minutes.push(0) %>
	<% @minutes.push(45.5) %>
	<% @minutes.sort! %>
	<% @score0 =0 %>
	<% @score1 =0 %>
	<% @score2 =0 %>
	<% @score3 =0 %>

	<% @minutes.each do |minute| %>
		<tr>
		  	<td>
		  		<% if minute == 0 %>
		  			<strong>Anpfiff</strong>
		  			<% elsif minute == 45.5 %>
		  			<strong>Halbzeit</strong>
		  			<% else %>
		  			'<%= minute %>
		  		<% end %>
		  	</td>
		  	<td>
		  		<% @match.corrections.each do |cor| %>
		  			<% if cor.minute == minute && cor.typeOfCorrection == 0 %>
		  				<%= link_to cor.name, cor.link, :target => "_blank" %>
		  				<% @score0 += cor.change %>
		  				<% @score1 += cor.change %>
		  				<% @score2 += cor.change %>
		  				<% @score3 += cor.change %>
	  				<% end%>
  				<% end %>
  			</td>

  			<td>
		  		<% @match.corrections.each do |cor| %>
		  			<% if cor.minute == minute && cor.typeOfCorrection == 1 %>
		  				<%= link_to cor.name, cor.link, :target => "_blank" %>
		  				<% @score1 += cor.change %>
	  				<% end%>
  				<% end %>
  			</td>

  			<td>
		  		<% @match.corrections.each do |cor| %>
		  			<% if cor.minute == minute && cor.typeOfCorrection == 2 %>
		  				<%= link_to cor.name, cor.link, :target => "_blank" %>
		  				<% @score2 += cor.change %>
	  				<% end%>
  				<% end %>
  			</td>

  			<td>
		  		<% @match.corrections.each do |cor| %>
		  			<% if cor.minute == minute && cor.typeOfCorrection == 3 %>
		  				<%= link_to cor.name, cor.link, :target => "_blank" %>
		  				<% @score3 += cor.change %>
	  				<% end%>
  				<% end %>
  			</td>
		</tr>
	<% end %>
		<tr>
			<th>
				Final
			</th>
			<th>
				<% @match.real_result = @score0 %>
				<%= @match.team1goals %> : <%= @match.team2goals %>
			</th>
			<th>
				<% @match.real_result = @score1 %>
				<%= @match.team1goals %> : <%= @match.team2goals %>
			</th>
			<th>
				<% @match.real_result = @score2 %>
				<%= @match.team1goals %> : <%= @match.team2goals %>
			</th>
			<th>
				<% @match.real_result = @score3 %>
				<%= @match.team1goals %> : <%= @match.team2goals %>
			</th>
		</tr>
</table>

<br><br>

<button><%= link_to "New Correction", new_correction_path(:match_id=>@match.id) %></button>

<br><br>



<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>