config/routes.rb
Rails.application.routes.draw do
  resources :corrections
  resources :matches
  resources :leagues
  get '/leagues/:id/add/:team_id' => 'leagues#addteam'
  resources :teams

  get '/tabelle' => 'pages#tabelle'
  get '/week/:league_id/:week_id' => 'pages#week'

end

app/models/correction.rb
class Correction < ActiveRecord::Base
	has_many :correctassos
	has_many :matches, :through => :correctassos

	def mirrorchange
		@mc = 0 
		@homegoals = (self.change - (self.change%10))/10
		@awaygoals = self.change % 10
		@mc = 10* @awaygoals + @homegoals
		@mc
	end

end

app/controllers/corrections_controller.rb
class CorrectionsController < ApplicationController
  before_action :set_correction, only: [:show, :edit, :update, :destroy]

  # GET /corrections
  # GET /corrections.json
  def index
    @corrections = Correction.all
  end

  # GET /corrections/1
  # GET /corrections/1.json
  def show
  end

  # GET /corrections/new
  def new
    @correction = Correction.new
    @match_id = params[:match_id].to_i
    if @match_id%2 == 1
      @match = Match.find(@match_id)
    else
      @match = Match.find(@match_id-1)
    end
  end

  # GET /corrections/1/edit
  def edit
  end

  # POST /corrections
  # POST /corrections.json
  def create
    @correction = Correction.new(correction_params)
    @correction.matches.push(Match.find(@correction.match_id))
    @correction.matches.push(Match.find(@correction.match_id+1))

    respond_to do |format|
      if @correction.save
        format.html { redirect_to match_path(@correction.match_id), notice: 'Correction was successfully created.' }
        format.json { render :show, status: :created, location: @correction }
      else
        format.html { render :new }
        format.json { render json: @correction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /corrections/1
  # PATCH/PUT /corrections/1.json
  def update
    respond_to do |format|
      if @correction.update(correction_params)
        format.html { redirect_to @correction, notice: 'Correction was successfully updated.' }
        format.json { render :show, status: :ok, location: @correction }
      else
        format.html { render :edit }
        format.json { render json: @correction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corrections/1
  # DELETE /corrections/1.json
  def destroy
    @correction.destroy
    respond_to do |format|
      format.html { redirect_to corrections_url, notice: 'Correction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_correction
      @correction = Correction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def correction_params
      params.require(:correction).permit(:name, :link, :match_id, :typeOfCorrection, :change, :minute)
    end
end

app/helpers/corrections_helper.rb
module CorrectionsHelper
end

app/views/corrections/edit.html.erb
<h1>Editing Correction</h1>

<%= form_for(@correction) do |f| %>
  <% if @correction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@correction.errors.count, "error") %> prohibited this correction from being saved:</h2>

      <ul>
      <% @correction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :match_id %><br>
    <%= f.number_field :match_id %>
  </div>
  <div class="field">
    <%= f.label :typeOfCorrection %><br>
    <%= f.number_field :typeOfCorrection %>
  </div>
  <div class="field">
    <%= f.label :change %><br>
    <%= f.number_field :change %>
  </div>
  <div class="field">
    <%= f.label :minute %><br>
    <%= f.number_field :minute %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @correction %> |
<%= link_to 'Back', corrections_path %>

app/views/corrections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Corrections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Link</th>
      <th>Match</th>
      <th>Type</th>
      <th>Change</th>
      <th>Minute</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @corrections.each do |correction| %>
      <tr>
        <td><%= correction.name %></td>
        <td><%= correction.link %></td>
        <td><%= correction.match_id %></td>
        <td><%= correction.typeOfCorrection %></td>
        <td><%= correction.change %></td>
        <td><%= correction.minute %></td>
        <td><%= link_to 'Show', correction %></td>
        <td><%= link_to 'Edit', edit_correction_path(correction) %></td>
        <td><%= link_to 'Destroy', correction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Correction', new_correction_path %>

app/views/corrections/new.html.erb
<h1>New Event
<% unless @match==nil %>
	for <br><strong><%= @match.team.name %> vs. <%= Team.find(@match.otherteam_id).name %></strong>
<% end %>
</h1>

<%= form_for(@correction) do |f| %>
  <% if @correction.errors.any? %>
	<div id="error_explanation">
	  <h2><%= pluralize(@correction.errors.count, "error") %> prohibited this correction from being saved:</h2>

	  <ul>
	  <% @correction.errors.full_messages.each do |message| %>
		<li><%= message %></li>
	  <% end %>
	  </ul>
	</div>
  <% end %>

  <div class="field">
	<%= f.label :name %><br>
	<%= f.text_field :name %>
  </div>
  <div class="field">
	<%= f.label :link %><br>
	<%= f.text_field :link %>
  </div>

  <% unless @match==nil %>
	<div class="field" style="display:none">
		<%= f.label :match_id %><br>
		<%= f.number_field :match_id, :value => @match.id %>
	</div>
  <% else %>
	<div class="field">
		We highly recommend using the match view to reach this page. You're welcome to manually input match id, but beware of mistakes.
		<%= f.label :match_id %><br>
		<%= f.number_field :match_id %>
	</div>
  <% end %>

  <div class="field">
	<%= f.label :typeOfCorrection %><br>
	<%= f.select :typeOfCorrection, [["Goal", 0], ["Referee Mistake", 1], ["Clear Chance", 2], ["Luck", 3]] %>
  </div>
  <div class="field">
	<%= f.label :change %><br>
	<%= f.select :change, [["#{@match.team.name} +1", 10], ["#{@match.team.name} -1", -10], ["#{Team.find(@match.otherteam_id).name} +1", 1], ["#{Team.find(@match.otherteam_id).name} -1", -1]] %>
  </div>
  <div class="field">
	<%= f.label :minute %><br>
	<%= f.number_field :minute, :min => 0 %>
  </div>

  <div class="actions">
	<%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', corrections_path %>

  
  

app/views/corrections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @correction.name %>
</p>

<p>
  <strong>Link:</strong>
  <%= @correction.link %>
</p>

<p>
  <strong>Match:</strong>
  <%= @correction.match_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @correction.typeOfCorrection %>
</p>

<p>
  <strong>Change:</strong>
  <%= @correction.change %>
</p>

<p>
  <strong>Minute:</strong>
  <%= @correction.minute %>
</p>


<%= link_to 'Edit', edit_correction_path(@correction) %> |
<%= link_to 'Back', corrections_path %>